# Versión del formato de docker-compose
version: '3.8'

services:
  # Nombre del servicio (puedes llamarlo como quieras)
  mysql:
    # Imagen oficial de MySQL versión 8
    image: mysql:8.0.33
    platform: linux/amd64
    # Reinicia el contenedor automáticamente si se cae
    restart: always
    environment:
      # Base de datos que se crea automáticamente
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Guarda los datos de la BD en un volumen (persistencia)
      # Evita que se borren al eliminar el contenedor

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      # Se asegura que MySQL arranque primero
      - mysql

  backend:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      # Se asegura que MySQL arranque primero
      - mysql
    env_file:
      - .env.test
    volumes:
      - ./:/app

volumes:
  # Definición del volumen nombrado
  mysql_data:
